---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: confighpas.confighpa.shareit.com
spec:
  group: confighpa.shareit.com
  names:
    kind: ConfigHpa
    plural: confighpas
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            downscaleForbiddenWindowSeconds:
              format: int32
              maximum: 600
              minimum: 1
              type: integer
            maxReplicas:
              format: int32
              maximum: 1000
              minimum: 1
              type: integer
            metrics:
              items:
                type: object
              type: array
            minReplicas:
              format: int32
              maximum: 1000
              minimum: 1
              type: integer
            scaleTargetRef:
              properties:
                apiVersion:
                  type: string
                kind:
                  type: string
                name:
                  type: string
              required:
                - kind
                - name
              type: object
            scaleUpLimitFactor:
              format: double
              maximum: 10
              minimum: 1
              type: number
            scaleUpLimitMinimum:
              format: int32
              maximum: 20
              minimum: 1
              type: integer
            tolerance:
              format: double
              maximum: 0.99
              minimum: 0.01
              type: number
            upscaleForbiddenWindowSeconds:
              format: int32
              maximum: 600
              minimum: 1
              type: integer
          required:
            - scaleTargetRef
            - maxReplicas
          type: object
        status:
          properties:
            conditions:
              items:
                type: object
              type: array
            currentMetrics:
              items:
                type: object
              type: array
            currentReplicas:
              format: int32
              type: integer
            desiredReplicas:
              format: int32
              type: integer
            lastScaleTime:
              format: date-time
              type: string
            observedGeneration:
              format: int64
              type: integer
          required:
            - currentReplicas
            - desiredReplicas
            - currentMetrics
            - conditions
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: config-hpa-controller
  namespace: kube-admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  - apiGroups:
      - '*'
    resources:
      - '*/scale'
    verbs:
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
  - apiGroups:
      - confighpa.shareit.com
    resources:
      - confighpas
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - metrics.k8s.io
    resources:
      - pods
    verbs:
      - list
  - apiGroups:
      - custom.metrics.k8s.io
    resources:
      - '*'
    verbs:
      - get
      - list
  - apiGroups:
      - external.metrics.k8s.io
    resources:
      - '*'
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
      - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manager-role
subjects:
  - kind: ServiceAccount
    name: config-hpa-controller
    namespace: kube-admin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-hpa-controller
  namespace: kube-admin
  labels:
    k8s-app: config-hpa-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: config-hpa-controller
  template:
    metadata:
      labels:
        k8s-app: config-hpa-controller
    spec:
      serviceAccountName: config-hpa-controller
      containers:
        - name: shpa
          image: "iyacontrol/config-hpa-controller:v0.1.0"
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi

---